# Introduction to NumPy

## NumPy Arrays

### From List

We will begin by creating a list.

In [1]:
my_list = [1,2,3]

Now, we will import the numpy library and cast this list as an array.

In [2]:
import numpy as np

np.array(my_list)

array([1, 2, 3])

To create a two-dimensional array, we can repeat this process but on a *list-of-lists*.

In [3]:
new_list = [[1,2,3],[4,5,6],[7,8,9]]

np.array(new_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Arange

A more direct route is to use the NumPy method *arange*.

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Add step-size as the third argument
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Zeros

We can also generate an array of zeros.

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### Ones

Or an array of ones.

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### Linspace

The NumPy method *linspace* will return a range of values that will be evenly spaced.

In [10]:
# The third argument is how many evenly spaced points you want returned
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

An Identity Matrix can also be constructed.

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random Numbers

In [12]:
np.random.rand(5)

array([0.73533904, 0.60577051, 0.13646906, 0.91310369, 0.61793016])

In [13]:
np.random.rand(5,5)

array([[0.83682735, 0.67006285, 0.6385029 , 0.16719426, 0.39064637],
       [0.44464692, 0.97696813, 0.26053491, 0.38349197, 0.28460922],
       [0.29999332, 0.73815665, 0.70107647, 0.61036651, 0.50574103],
       [0.79233227, 0.8029456 , 0.46635982, 0.27503976, 0.24274529],
       [0.20100789, 0.50990957, 0.30122812, 0.96712118, 0.44582367]])

You can also also return random numbers from a **Standard Normal Distribution**.

In [14]:
np.random.randn(5)

array([ 0.2962684 ,  0.17237687,  0.53268474, -0.31468019,  1.68081689])

Finally, random *integers* can be generated between two values.

In [15]:
np.random.randint(1,100)

18

In [16]:
# The third argument is the number of random integers you want returned
np.random.randint(1,100, 5)

array([97, 26, 58, 83, 55])

### Reshape

In [17]:
arr = np.random.randint(1,100,10)

In [18]:
arr.reshape(2,5)

array([[76, 17, 82, 26, 54],
       [40, 52, 48, 99, 97]])

### Max / Min

In [19]:
arr.max()

99

In [20]:
arr.min()

17

We can also return the location of the maximum value in an array.

In [21]:
arr.argmax()

8

### Shape

In [22]:
arr.shape

(10,)

### Data Type

In [23]:
arr.dtype

dtype('int32')