# Introduction to NumPy

## NumPy Arrays

### From List

We will begin by creating a list.

In [1]:
my_list = [1,2,3]

Now, we will import the numpy library and cast this list as an array.

In [2]:
import numpy as np

np.array(my_list)

array([1, 2, 3])

To create a two-dimensional array, we can repeat this process but on a *list-of-lists*.

In [3]:
new_list = [[1,2,3],[4,5,6],[7,8,9]]

np.array(new_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Arange

A more direct route is to use the NumPy method *arange*.

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Add step-size as the third argument
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Zeros

We can also generate an array of zeros.

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### Ones

Or an array of ones.

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### Linspace

The NumPy method *linspace* will return a range of values that will be evenly spaced.

In [10]:
# The third argument is how many evenly spaced points you want returned
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

An Identity Matrix can also be constructed.

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random Numbers

In [12]:
np.random.rand(5)

array([0.56712107, 0.57479802, 0.12748355, 0.27723599, 0.71105463])

In [13]:
np.random.rand(5,5)

array([[0.69804297, 0.19291531, 0.52974126, 0.11005382, 0.53078402],
       [0.96325845, 0.25042803, 0.22675216, 0.76534463, 0.36624053],
       [0.75141537, 0.45823256, 0.17574082, 0.59962617, 0.36320921],
       [0.99560438, 0.4371236 , 0.98789855, 0.57218084, 0.22853523],
       [0.17273342, 0.65911434, 0.47656733, 0.60379921, 0.27499931]])

You can also also return random numbers from a **Standard Normal Distribution**.

In [14]:
np.random.randn(5)

array([-2.03912327, -0.02747192,  0.51456813, -0.69122328,  0.47385538])

Finally, random *integers* can be generated between two values.

In [15]:
np.random.randint(1,100)

36

In [16]:
# The third argument is the number of random integers you want returned
np.random.randint(1,100, 5)

array([ 7, 12,  8, 99, 50])

### Reshape

In [17]:
arr = np.random.randint(1,100,10)

In [18]:
arr.reshape(2,5)

array([[77, 51, 84, 17, 56],
       [88, 99, 82, 15,  3]])

### Max / Min

In [19]:
arr.max()

99

In [20]:
arr.min()

3

We can also return the location of the maximum value in an array.

In [21]:
arr.argmax()

6

### Shape

In [22]:
arr.shape

(10,)

### Data Type

In [23]:
arr.dtype

dtype('int32')