# NumPy Array Indexing

## Indexing and Selection

In [1]:
import numpy as np

In [2]:
# Create a sample array
arr = np.arange(0,11)

### Select single element

In [3]:
arr[8]

8

### Select a slice

In [4]:
arr[3:7]

array([3, 4, 5, 6])

In [5]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

### Broadcasting

We can broadcast a value to a slice of an array.

In [6]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### Copy Array

If you want a copy of an array rather than just a reference to an existing array, do this:

In [7]:
arr_copy = arr.copy()

## 2D Array

In [8]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Get element

In [9]:
arr_2d[0][0]

5

### Slice of 2D Array

In [10]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

## Comparison Operators

In [11]:
arr = np.arange(0,11)

In [12]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [13]:
bool_arr = arr > 5
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

We can achieve a similar affect with this:

In [14]:
arr[arr >5]

array([ 6,  7,  8,  9, 10])